name: amap_map_fluttify
description: An `Amap` map component, based on `fluttify` engine.
version: 0.5.3+d62f0ad
author: yohom <382146139@qq.com>
homepage: https://github.com/fluttify-project/amap_map_fluttify

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  foundation_fluttify: ^0.0.9
  amap_core_fluttify: ^0.0.11+a9797a4
  url_launcher: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.yohom.amap_map_fluttify
    pluginClass: AmapMapFluttifyPlugin